xuchen:
  module:
    request:
      log: true
spring:
  redis:
    host: localhost
    password: password
    port: 16379
    database: 1
    timeout: 300
server:
  tomcat:
    threads:
      max: 1
