xuchen:
  module:
    request:
      log: true
    log:
      app-name: web-cache-demo
      enable-file: false
spring:
  redis:
    host: localhost
    password: password
    port: 16379
    database: 1
    timeout: 300
